// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8YWaDVezq8HcuYrG8fcxR6OriVjW7dNQ',
    appId: '1:1074972795804:web:d3e07455e2ffd124f6de59',
    messagingSenderId: '1074972795804',
    projectId: 'vareva-mobile',
    authDomain: 'vareva-mobile.firebaseapp.com',
    storageBucket: 'vareva-mobile.appspot.com',
    measurementId: 'G-LDVCVBYQS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKGXTmKL_xRIh5l_6fnqM-OKrUEmx6xcY',
    appId: '1:1074972795804:android:b50982870f63050df6de59',
    messagingSenderId: '1074972795804',
    projectId: 'vareva-mobile',
    storageBucket: 'vareva-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFX6cd_hZ6_hKHW-rtmRfpD1rvDs40oKE',
    appId: '1:1074972795804:ios:6586ac0c5633887bf6de59',
    messagingSenderId: '1074972795804',
    projectId: 'vareva-mobile',
    storageBucket: 'vareva-mobile.appspot.com',
    androidClientId: '1074972795804-rlt7cra5bc3nvgkjojcf1oplch1at19h.apps.googleusercontent.com',
    iosClientId: '1074972795804-9cgsvhorf5mvbirpkttd27140lr5og9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.vartarevartaMagazine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFX6cd_hZ6_hKHW-rtmRfpD1rvDs40oKE',
    appId: '1:1074972795804:ios:7d1f363521775ee4f6de59',
    messagingSenderId: '1074972795804',
    projectId: 'vareva-mobile',
    storageBucket: 'vareva-mobile.appspot.com',
    androidClientId: '1074972795804-rlt7cra5bc3nvgkjojcf1oplch1at19h.apps.googleusercontent.com',
    iosClientId: '1074972795804-ma07ctovms7g2tklves2q6lv2evvh02g.apps.googleusercontent.com',
    iosBundleId: 'com.example.vartarevartaMagazine.RunnerTests',
  );
}
